### ISSUE TITLE
http 400 bad request on run

### ISSUE THREAD

**Issue by e30chris** [pmorton/prime_platform#1]
attempting to run prime_platform and receiving a `HTTP/1.1 400 Bad Request `

steps to repro:

- `go run main.go`

results:

```
prime_platform/ on master
› curl -v http://127.0.0.1:9090
* Rebuilt URL to: http://127.0.0.1:9090/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9090 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Mon, 20 Aug 2018 20:30:23 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by e30chris** [comment]
also verified the same `HTTP 400` when the Go was updated to test two prime numbers.

**Comment by pmorton** [comment]
Hi @e30chris I have updated the repo with testing instructions for the server in #2 . Essentially you should use a get request parameter called `test` to submit your prime number. 

For example:
`curl -v "localhost:9090?test=2"`
